export enum IpcEvent {
  ENTRY_CREATED='IPC_EVENT.ENTRY_CREATED',
  REGISTER_TAB='IPC_EVENT.REGISTER_TAB',
  ADD_ENTRY='IPC_EVENT.ADD_ENTRY',
  REQUEST_CACHED_URLS='IPC_EVENT.REQUEST_CACHED_URLS',
  RESPONSE_CACHED_URLS='IPC_EVENT.RESPONSE_CACHED_URLS',
  FORWARD_TO_POPUP='IPC_EVENT.FORWARD_TO_POPUP'
}